---
title: "Overview of time-to-event design articles"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: gsDesign.bib
vignette: >
  %\VignetteIndexEntry{Overview of time-to-event endpoint design articles}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE,message=FALSE,warning=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

options( width = 58 )

```

Due to the many issues involved, topics on design for time-to-event endpoints have been divided into several vignettes.

- [Basic time-to-event design](gsSurvBasicExamples.html)
    - Design with constant enrollment, failure rate and dropout assumptions
    - Design with fixed study duration
    - Table output with footnoting using the **gt** package
    - Standard plots available for designs
    - Updating study bounds based on event counts at analyses
- [Enrollment and event accumulation](EnrollmentAndEventAccumulation.html)
    - Designing with changing enrollment and failure rates over time
    - Design with fixed enrollment rates, varying enrollment duration to achieve
    - Expected event accumulation
        - `nEventsIA()` to describe expected event accumulation over time for a design
        - Expected event accumulation by treatment group under possibly non-proportional hazards assumptions using `eEvents()`
- [Approximating cure models and calendar-based spending](gsSurvCureModel.html)
    - Exponential with cure model
    - Poisson mixture cure model
    - Calendar-based spending and interim analysis timing
        - Updating spending at time of analysis
- [Designing for multiple hypotheses](gsSurvForMultipleHypotheses.html)
    - Stratified populations
    - Sequential p-values
    - Graphical multiplicity implementation using the **gMCP** package
