LIBR = "-L$(R_HOME)/bin/i386 -lR -L../inst/libs/i386"

all:
	mkdir -p ../explorergui-build
	cd ../explorergui-build
	cmake -G "NMake Makefiles" ../src -DR_LIBRARIES=${LIBR} -DR_INCLUDES=${R_INCLUDE_DIR} -DCMAKE_INSTALL_PREFIX=../inst/libs/i386/
	nmake install
	cp -R ../src/images/ ../inst

clean:
	rm -rf ../explorergui-build; \
	rm -rf ../inst/libs; \
	rm -rf ../inst/images


