LIBR = "-L$(R_HOME)/bin/i386 -lR -L../inst/libs/i386"

all:
	cd ../explorergui-build
	nmake install
	cp -R ../src/images/ ../inst

clean:
	rm -rf ../explorergui-build
	rm -rf ../inst/libs
	rm -rf ../inst/images

