# the following should produce errors
gsPP(x=1)
x <- gsDesign()
x1 <- gsDesign(test.type=1)
gsPP(x=x, i=x$k)
gsPP(x=x1, i=1, zi=-25)
gsPP(x=x, i=1, zi=2*x$upper$bound[1])
gsPP(x=x, i=2, zi=-20)
gsPP(x=x, i=1, zi="text")
gsPP(x=x, i=1, zi=x$upper$bound[1], theta="text")
gsPP(x=x, i=1, zi=x$upper$bound[1], wgts="text")
gsPP(x=x, i=1, zi=x$upper$bound[1], wgts=c(1,2,3))
gsPP(x=x, i=1, zi=x$upper$bound[1], r=0)
gsPP(x=x, i=1, zi=x$upper$bound[1], r=81)
