#' Translate survival design bounds to exact binomial bounds
#'
#' @param x An object of class \code{gsSurv}; i.e., an object generated by
#'   the \code{gsSurv()} function.
#' @param observedEvents If NULL (default), targeted timing of analyses will come from \code{x$n.I}. 
#' Otherwise, this should be vector of increasing positive integers with at most 1 value \code{>= x$n.IPlan} and of length at least 2.
#' Only one value can be greater than or equal to \code{x$maxn.IPlan}. 
#' This determines the case count at each analysis performed. 
#' Primarily, this is used for updating a design at the time of analysis.
#' @param alpha Optional alpha level for deriving updated exact efficacy bounds.
#'   If \code{NULL}, the alpha level from \code{x} is used.
#' @param usTime Optional upper spending-time override (length \code{k} or
#'   \code{k - 1}, with final value appended as 1 if needed). If \code{NULL},
#'   this defaults to \code{observedEvents / x$maxn.IPlan} (capped at 1) when
#'   \code{observedEvents} is supplied, or to the planned design timing
#'   otherwise.
#' @param lsTime Optional lower spending-time override for \code{test.type = 4}
#'   or \code{6}
#'   (same length and monotonicity requirements as \code{usTime}). If
#'   \code{NULL}, it defaults to \code{usTime}.
#' @param maxSpend Logical scalar. If `TRUE`, force full alpha spending (and, for
#'   `test.type = 4`, full beta spending; for `test.type = 6`, full lower-bound
#'   spending under the null) at the final analysis even when
#'   `observedEvents[k] < x$maxn.IPlan`. This keeps earlier analysis spending
#'   unchanged and applies the override only at the last look.
#' 
#' @details
#' Test types 1 (one-sided), 4 (non-binding beta-spending futility), and 6
#' (non-binding lower-bound spending under the null) are supported for full
#' conversion.
#' The current \code{gsBinomialExact} object contains one lower efficacy bound
#' and one upper stopping bound. Consequently, it cannot represent the
#' separate futility and harm bounds required by test types 7 and 8. Binding
#' designs (types 2, 3, 5, and 7) are outside the non-binding exact-efficacy
#' framework. Exact repeated and sequential efficacy
#' p-values can nevertheless be computed for non-binding types 1, 4, 6, and 8
#' with \code{repeatedPValueBinomialExact()} and
#' \code{sequentialPValueBinomialExact()}, which intentionally ignore
#' non-binding lower and harm bounds.
#'
#' The exact binomial routine \code{gsBinomialExact} has requirements that may not be satisfied
#' by the initial asymptotic approximation. 
#' Thus, the approximations are updated to satisfy the following requirements of \code{gsBinomialExact}:
#' \code{a} (the efficacy bound) must be positive, non-decreasing, and strictly less than n.I
#' \code{b} (the upper event-count stopping bound for futility or the Type 6
#' lower bound) must be positive, non-decreasing, and strictly greater than a
#' \code{n.I - b} must be non-decreasing and >= 0
#'
#' With `observedEvents`, spending times are based on
#' \code{observedEvents / x$maxn.IPlan}. If \code{maxSpend = TRUE}, the final
#' spending time is set to 1 so all remaining spending is used at the last look.
#' If \code{x$testLower} is present (for example from \code{gsSurv()} with
#' selective lower-bound looks), lower-bound spending is flattened at analyses
#' where \code{testLower = FALSE}.
#' 
#' @return An object of class \code{gsBinomialExact}. The returned object also
#'   records `test.type`, `alpha`, applicable `astar`, and `testLower`. For
#'   `test.type = 6`, the exact object's upper event-count bound represents the
#'   non-binding lower stopping bound, with its first probability column
#'   calibrated under the null hypothesis.
#'
#' @seealso \code{\link{gsBinomialExact}}
#'
#' @export
#'
#' @examples
#' # The following code derives the group sequential design using the method
#' # of Lachin and Foulkes
#'
#' x <- gsSurv(
#'   k = 3,                 # 3 analyses
#'   test.type = 4,         # Non-binding futility bound 1 (no futility bound) and 4 are allowable
#'   alpha = .025,          # 1-sided Type I error
#'   beta = .1,             # Type II error (1 - power)
#'   timing = c(0.45, 0.7), # Proportion of final planned events at interims
#'   sfu = sfHSD,           # Efficacy spending function
#'   sfupar = -4,           # Parameter for efficacy spending function
#'   sfl = sfLDOF,          # Futility spending function; not needed for test.type = 1
#'   sflpar = 0,            # Parameter for futility spending function
#'   lambdaC = .001,        # Exponential failure rate
#'   hr = 0.3,              # Assumed proportional hazard ratio (1 - vaccine efficacy = 1 - VE)
#'   hr0 = 0.7,             # Null hypothesis VE
#'   eta = 5e-04,           # Exponential dropout rate
#'   gamma = 10,            # Piecewise exponential enrollment rates
#'   R = 16,                # Time period durations for enrollment rates in gamma
#'   T = 24,                # Planned trial duration
#'   minfup = 8,            # Planned minimum follow-up
#'   ratio = 3              # Randomization ratio (experimental:control)
#' )
#' # Convert bounds to exact binomial bounds
#' toBinomialExact(x)
#' # Update bounds at time of analysis
#' toBinomialExact(x, observedEvents = c(20,55,80))
#' # Update exact efficacy bounds using a different alpha level
#' toBinomialExact(x, observedEvents = c(20,55,80), alpha = 0.01)
#' # Explicit spending-time override
#' toBinomialExact(x, observedEvents = c(20, 55, 80), usTime = c(.25, .65, 1))
#' # Optionally force full spending at final look when final events are below plan
#' toBinomialExact(x, observedEvents = c(20, 55, 75), maxSpend = TRUE)
toBinomialExact <- function(x, observedEvents = NULL, alpha = NULL, usTime = NULL, lsTime = NULL, maxSpend = FALSE) {
  if (!inherits(x, "gsSurv")) stop("toBinomialExact must have class gsSurv as input")
  if (!(x$test.type %in% c(1, 4, 6))) {
    reason <- switch(
      as.character(x$test.type),
      `2` = "symmetric two-sided boundaries are not represented by the exact lower-tail efficacy conversion",
      `3` = "binding futility bounds are outside the non-binding exact-efficacy framework",
      `5` = "binding lower bounds are outside the non-binding exact-efficacy framework",
      `7` = "binding futility and harm bounds are outside the non-binding exact-efficacy framework",
      `8` = "gsBinomialExact has only two boundaries and cannot separately represent futility and harm",
      "this test type is not supported"
    )
    stop(
      "toBinomialExact input test.type must be 1, 4, or 6; test.type = ",
      x$test.type, " is unsupported because ", reason,
      call. = FALSE
    )
  }
  if (is.null(alpha)) {
    alpha <- x$alpha
  } else if (!is.numeric(alpha) || length(alpha) != 1 || !is.finite(alpha) || alpha <= 0 || alpha >= 1) {
    stop("toBinomialExact: alpha must be a finite numeric scalar in (0, 1)")
  }
  if (!is.logical(maxSpend) || length(maxSpend) != 1 || is.na(maxSpend)) {
    stop("toBinomialExact: maxSpend must be TRUE or FALSE")
  }
  astar_tracks_complement <- x$test.type == 6 &&
    isTRUE(all.equal(x$astar, 1 - x$alpha, tolerance = 1e-7))
  effective_astar <- if (astar_tracks_complement) 1 - alpha else x$astar
  if (x$test.type == 6 && effective_astar > 1 - alpha) {
    stop(
      "toBinomialExact: alpha override requires astar <= 1 - alpha for test.type = 6",
      call. = FALSE
    )
  }
  if (x$test.type == 1 && !is.null(lsTime)) {
    stop("toBinomialExact: lsTime can only be specified for test.type = 4 or 6")
  }
  # Round interim sample size (or events for gsSurv object)
  xx <- if (max(round(x$n.I) != x$n.I)) toInteger(x) else x
  planned_final_events <- xx$n.I[x$k]
  if(is.null(observedEvents)){
    counts <- xx$n.I
    k <- xx$k
  }else{
    if (!isInteger(observedEvents)) stop("toBinomialExact: observedEvents must be a vector of increasing positive integers")
    if (min(observedEvents - dplyr::lag(observedEvents, default = 0)) < 1) 
      stop("toBinomialExact: observedEvents must be a vector of increasing positive integers")
    counts <- observedEvents
    if (sum(observedEvents >= xx$maxn.IPlan) > 1) stop("toBinomialExact: at most 1 value in observedEvents can be >= maximum planned (x$maxn.IPlan)")
    k <- length(observedEvents)
    if (k < 2) stop("toBinomialExact: must have at least 2 values in observedEvents")
  }
  if (!is.null(observedEvents) || !isTRUE(all.equal(alpha, x$alpha))) {
    xx <- gsDesign(
      k = k,
      test.type = x$test.type,
      alpha = alpha,
      beta = x$beta,
      astar = effective_astar,
      sfu = x$upper$sf,
      sfupar = x$upper$param,
      sfl = x$lower$sf,
      sflpar = x$lower$param,
      n.I = counts,
      maxn.IPlan = planned_final_events,
      delta = x$delta,
      delta1 = x$delta1,
      delta0 = x$delta0
    )
    xx$hr0 <- x$hr0
  }
  # Translate vaccine efficacy to exact binomial probabilities

  p0 <- x$hr0 * x$ratio / (1 + x$hr0 * x$ratio)
  p1 <- x$hr * x$ratio / (1 + x$hr * x$ratio)
  # Lower bound probabilities are for efficacy and Type I error should be controlled under p0
  a <- qbinom(p = pnorm(-xx$upper$bound), size = counts, prob = p0) - 1
  init_approx <- list(a = a) # save initial efficacy bound approximation

  # check that a is non-decreasing, >= -1, and < n.I
  a <- pmax(a, -1)
  a <- pmax(a, dplyr::lag(a, def = -1))
  a <- pmin(a, counts - 1)

  atem <- a
  default_timing <- pmin(counts / xx$maxn.IPlan, 1)
  timing <- resolveSpendingTime(
    spendingTime = usTime,
    defaultTime = default_timing,
    k = k,
    label = "usTime"
  )
  timingl <- resolveSpendingTime(
    spendingTime = lsTime,
    defaultTime = timing,
    k = k,
    label = "lsTime"
  )
  if (isTRUE(maxSpend)) {
    timing[k] <- 1
    timingl[k] <- 1
  }
  if (sum(timing >= 1) > 1) {
    stop("toBinomialExact: usTime must have at most 1 value >= 1")
  }
  if (x$test.type %in% c(4, 6) && sum(timingl >= 1) > 1) {
    stop("toBinomialExact: lsTime must have at most 1 value >= 1")
  }
  alpha_spend <- xx$upper$sf(alpha = alpha, t = timing, param = xx$upper$param)$spend
  if (x$test.type != 1) {
    # Upper event-count probabilities represent the non-binding lower stopping
    # bound (beta-spending futility for Type 4; H0 spending for Type 6).
    b <- qbinom(p = pnorm(-xx$lower$bound), size = counts, prob = p0)
    init_approx$b <- b # save initial upper event-count bound approximation

    # check that b is non-decreasing, > a, and n.I - b is non-decreasing
    b <- pmin(b, counts + 1)
    b <- pmax(a + 1, b)
    b <- pmin(b, counts - dplyr::lag(counts, def = 0) + dplyr::lag(b, def = 1))
    # Type 4 targets beta spending under H1. Type 6 targets lower-bound
    # spending under H0.
    lower_spend_total <- if (x$test.type == 4) xx$beta else xx$astar
    lower_spend <- xx$lower$sf(
      alpha = lower_spend_total,
      t = timingl,
      param = xx$lower$param
    )$spend
    active_lower <- rep(TRUE, k)
    if (!is.null(x$testLower)) {
      active_lower <- x$testLower
      if (length(active_lower) == 1) active_lower <- rep(active_lower, k)
      if (length(active_lower) == k) {
        for (i in seq_len(k)) {
          if (!isTRUE(active_lower[i])) {
            lower_spend[i] <- if (i == 1) 0 else lower_spend[i - 1]
          }
        }
      }
    }
  } else {
    b <- counts + 1 # test.type = 1 means no futility bound
  }
  for (j in 1:k) {
    # Non-binding bound assumed.
    # Compute spending through analysis j.
    # Upper bound set to > counts so that it cannot be crossed;
    # this is to compute lower bound spending with non-binding futility bound.
    # NOTE: cannot call gsBinomialExact with k == 1, so make it at least 2
    # cumulative spending through analysis j
    nblowerprob <- sum(gsBinomialExact(
      k = max(j, 2), theta = p0, n.I = counts[1:max(j, 2)],
      a = a[1:max(j, 2)], b = counts[1:max(j, 2)] + 1
    )$lower$prob[1:j])
    atem <- a # Work space for updating efficacy bound
    btem <- b # Work space for updating futility bound
    # Set range for possible changes to a[j]
    amin <- ifelse(j > 1, a[j - 1], -1)
    amax <- ifelse(j < k, counts[j] - 1, counts[j])
    a[j] <- ifelse(a[j] > amax, amax, a[j])
    a[j] <- ifelse(a[j] < amin, amin, a[j])
    if (amin > amax) stop(paste("toBinomialExact: amin > amax: amin =", amin, "amax =", amax, "j =", j))
    atem[j] <- a[j]
    # If less than allowed spending, check if bound can be increased
    if (nblowerprob < alpha_spend[j]) {
      while (nblowerprob < alpha_spend[j]) {
        a[j] <- atem[j]
        if (a[j] >= amax - 1) break # keep in allowable range 
        atem[j] <- atem[j] + 1
        nblowerprob <- sum(gsBinomialExact(
          k = max(j, 2), theta = p0, n.I = counts[1:max(j, 2)],
          a = atem[1:max(j, 2)], b = counts[1:max(j, 2)] + 1
        )$lower$prob[1:j])
      }
      # If > allowed spending, reduce bound appropriately
    } else if (nblowerprob > alpha_spend[j]) {
      while (nblowerprob > alpha_spend[j]) {
        a[j] <- a[j] - 1
        nblowerprob <- sum(gsBinomialExact(
          k = max(j, 2), theta = p0, n.I = counts[1:max(j, 2)],
          a = a[1:max(j, 2)], b = counts[1:max(j, 2)] + 1
        )$lower$prob[1:j])
      }
    }
    # beta-spending, if needed
    if (x$test.type == 4) {
      # Set range for possible values of b[j]
      bmin <- a[j] + 1 # must be strictly > a[j]
      bmin <- ifelse(j == 1, bmin, max(bmin, b[j - 1])) # must be non-decreasing 
      bmax <- counts[j] + 1
      bmax <- ifelse(j == 1, bmax, min(bmax, counts[j] - counts[j - 1] + b[j - 1]))
      if (bmin > bmax) stop(paste("bmin > bmax: bmin =", bmin, "bmax =", bmax, "j =", j))
      b[j] <- ifelse(b[j] > bmax, bmax, b[j])
      b[j] <- ifelse(b[j] < bmin, bmin, b[j])
      btem[j] <- b[j]
      upperprob <- sum(gsBinomialExact(
        k = max(j, 2), theta = p1, n.I = counts[1:max(j, 2)],
        a = a[1:max(j, 2)], b = b[1:max(j, 2)]
      )$upper$prob[1:j])
      if (upperprob < lower_spend[j]) {
        while (upperprob < lower_spend[j]) {
          b[j] <- btem[j]
          if (btem[j] == bmin) break # only lower if range allows
          btem[j] <- btem[j] - 1
          upperprob <- sum(gsBinomialExact(
            k = max(j, 2), theta = p1, n.I = counts[1:max(j, 2)],
            a = a[1:max(j, 2)], b = btem[1:max(j, 2)]
          )$upper$prob[1:j])
        }
        
      } else if (upperprob > lower_spend[j]) {
        while (upperprob > lower_spend[j] &&
               b[j] < bmax) {
          b[j] <- b[j] + 1
          upperprob <- sum(gsBinomialExact(
            k = max(j, 2), theta = p1, n.I = counts[1:max(j, 2)],
            a = a[1:max(j, 2)], b = b[1:max(j, 2)]
          )$upper$prob[1:j])
        }
      }
    } else if (x$test.type == 6) {
      # Type 6 uses the same exact two-bound recursion, but chooses the upper
      # event-count boundary to spend under H0 rather than under H1.
      bmin <- a[j] + 1
      bmin <- ifelse(j == 1, bmin, max(bmin, b[j - 1]))
      bmax <- counts[j] + 1
      bmax <- ifelse(
        j == 1,
        bmax,
        min(bmax, counts[j] - counts[j - 1] + b[j - 1])
      )
      if (bmin > bmax) {
        stop(paste("bmin > bmax: bmin =", bmin, "bmax =", bmax, "j =", j))
      }

      # No boundary crossing is allowed at an inactive lower look.
      if (!isTRUE(active_lower[j])) {
        b[j] <- bmax
      } else if (j == k && astar_tracks_complement && timingl[j] >= 1) {
        # With default astar = 1 - alpha and full spending, use the smallest
        # allowable upper bound so the final decision regions are exhaustive
        # to the extent permitted by monotone integer boundaries.
        b[j] <- bmin
      } else {
        candidates <- seq.int(bmin, bmax)
        upper_probability <- vapply(candidates, function(candidate) {
          if (j == 1) {
            return(stats::pbinom(
              q = candidate - 1,
              size = counts[j],
              prob = p0,
              lower.tail = FALSE
            ))
          }
          b_candidate <- b[seq_len(j)]
          b_candidate[j] <- candidate
          sum(gsBinomialExact(
            k = j,
            theta = p0,
            n.I = counts[seq_len(j)],
            a = a[seq_len(j)],
            b = b_candidate
          )$upper$prob[, 1])
        }, numeric(1))
        allowed <- which(
          upper_probability <= lower_spend[j] * (1 + 1e-10) +
            .Machine$double.xmin
        )
        b[j] <- if (length(allowed) > 0) {
          candidates[allowed[which.max(upper_probability[allowed])]]
        } else {
          bmax
        }
      }
    }
  }
  xxxx <- gsBinomialExact(k = k, theta = c(p0, p1), n.I = counts, a = a, b = b)
  xxxx$init_approx <- init_approx
  xxxx$test.type <- x$test.type
  xxxx$alpha <- alpha
  xxxx$astar <- if (x$test.type == 6) xx$astar else NULL
  xxxx$testLower <- if (x$test.type == 1) NULL else active_lower
  return(xxxx)
}

resolveSpendingTime <- function(spendingTime, defaultTime, k, label) {
  if (is.null(spendingTime)) {
    return(defaultTime)
  }
  if (!is.numeric(spendingTime) || any(!is.finite(spendingTime))) {
    stop("toBinomialExact: ", label, " must be numeric")
  }
  if (!(length(spendingTime) %in% c(k - 1, k))) {
    stop("toBinomialExact: ", label, " must have length k or k-1")
  }
  if (length(spendingTime) == k - 1) {
    spendingTime <- c(spendingTime, 1)
  }
  if (any(spendingTime <= 0) || any(diff(spendingTime) <= 0)) {
    stop("toBinomialExact: ", label, " must be strictly increasing and positive")
  }
  spendingTime
}
