

all : setenv
	cd ..
	R CMD INSTALL --no-clean-on-error gsDesignExplorer

create-r-import-lib :
	pushd $(RPATH)\bin\i386
	tools\DLLImportTool\ImgDef.exe R.dll > R.def
	popd
	mv $(RPATH)\bin\i386\R.def libs\msvc\R\R-2.13.1
	lib /machine:x86 /subsystem:windows /def:libs\msvc\R\R-2.13.1\R.def /out:libs\msvc\R\R-2.13.1\R.lib


setenv :
	# gsDesignExplorer project base directory
	set PROJECTROOT=$(CD)

	# PATH TO VISUAL STUDIO TOOLCHAIN
	# ===============================
	set INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include;
	set LIB=C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\ATLMFC\LIB;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\lib;
	set LIBPATH=C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Windows\Microsoft.NET\Framework\v3.5;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\ATLMFC\LIB;
	set VSPATH=C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Windows\Microsoft.NET\Framework\v3.5;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin\NETFX 4.0 Tools;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin;

	# PATH TO INSTALLED TOOLS
	# =======================
	set RPATH=C:\dev\tools\R\R-2.13.1
	# RTOOLS=C:\dev\tools\Rtools
	# QTDIR=C:\QtSDK\Desktop\Qt\4.7.3\MSVC2008

	# PATH TO VERSIONED TOOLS
	# =======================
	set QTDIR=$(PROJECTROOT)\libs\msvc\Qt\4.7.3\msvc2008

	set PATH=$(VSPATH);$(QTDIR)\bin;$(RPATH)\bin;$(PATH);C:\dev\tools\cmake\cmake-2.8.4\bin

dispenv : setenv
	@echo INCLUDE=$(INCLUDE)
	@echo LIB=$(LIB)
	@echo LIBPATH=$(LIBPATH)
	@echo PATH=$(PATH)
	@echo PROJECTROOT=$(PROJECTROOT)
	@echo QTDIR=$(QTDIR)
	@echo RPATH=$(RPATH)
	@echo VSPATH=$(VSPATH)


